name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test (${{ matrix.os }} / ${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]

        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup compiler
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            sudo apt install -y g++ cache
          else
            sudo apt install -y clang clang++ ccache
          fi

      - name: Enable ccahe
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++

      - name: Run clang-tidy
        run: clang-tidy -p build $(git ls-files '*.cpp')

      - name: Build
        run: cmake --build build --config Release --parallel 4

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Upload build artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.compiler }}
          path: build/
